src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
Use the new API induced by better handling of snippets in kiwix-lib.
=> Update to the new API of kiwix-lib.

meson.build, src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
To merge once the https://github.com/kiwix/kiwix-lib/pull/42 PR has been merged.
=> Search in libzim

static/server/taskbar.css, static/server/taskbar.html.part
The taskbar (topbar containing btns "home", "library" and "random" is now responsive
=> #336 taskbar is now responsive

Changelog, meson.build
=> Dump the version to 0.2.

static/meson.build, travis/install_deps.sh
This changes has been created by @legoktm in PR #63 
This is just a rebase on top of master to avoid "complex" git history.
See https://github.com/kiwix/kiwix-lib/pull/76
=> Look for renamed kiwix-compile-resources script as well

src/server/kiwix-serve.cpp
=> Make kiwix-server multi-threaded.

src/server/kiwix-serve.cpp, static/server/global_taskbar.html.part, static/server/home.html.tmpl, static/server/include.html.part, static/server/taskbar.html.part
This PR is small rewrite of the PR #85 created by @swiftugandan.
I've created a new PR as the original one is on the swiftugandan's repository and I have no write access on his repository.
=> Swiftugandan root

src/server/kiwix-serve.cpp
This use the small API of kiwix-lib and so, cannot search a text query
and filter around a geo position in the same time.
There is no way to do a search but than write directly the search url
by hand.
If the request is wrongly formatted, the search is simply not done without
error message.
=> Add a small (private) support for geo query.

src/server/kiwix-serve.cpp
=> Better search handling

src/server/kiwix-serve.cpp
Related to kiwix/kiwix-lib#123
=> Update kiwix-serve to the new kiwix-lib API.

src/server/kiwix-serve.cpp
=> fix static resources on home page when using --nosearchbar

Changelog, src/manager/kiwix-manage.cpp
=> Proper exit code

Changelog, src/server/kiwix-serve.cpp, static/server/global_taskbar.html.part, static/server/taskbar.html.part
=> Improved taskbar #160 #59

src/server/request_context.cpp, src/server/request_context.h
=> Fix #217: RequestContext::connection is unused

src/manager/kiwix-manage.cpp, src/server/kiwix-serve.cpp, static/server/opensearchdescription.xml
Adapt to https://github.com/kiwix/kiwix-lib/pull/170
Do not merge.
=> WIP New kiwix lib api

src/manager/kiwix-manage.cpp
=> Be able to remove several books in a single command.

src/man/kiwix-manage.1
And change one of the URLs to HTTPS, and remove a reference
to the removed kiwix-install(1).
=> Improve grammar in kiwix-manage.1

src/man/kiwix-serve.1
Minor grammar fixes and remove reference to kiwix-install(1).
=> Improve kiwix-serve.1

src/server/kiwix-serve.cpp
=> Initialize geoquery variables.

src/manager/kiwix-manage.cpp, src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
Now that kiwix-lib do not handle external index, we must not try to handle
it ourselves.
See kiwix/kiwix-lib#190.
Fix #245
=> Do not handle external index.

src/server/kiwix-serve.cpp
If the entry is a redirection, we should redirect the client to the
right entry instead of serving the target content.
As we are doing a redirection, urls are good and we don't have to change
link inside the html or css content.
Fix #192
=> [server] Correctly implement 302 redirection if the entry is a redirection

src/server/kiwix-serve.cpp
We still need to change the html content to handle absolute url in zims.
Issue has been introduced by commit 978dc47. Some code was not related
to redirection but to absolute url. I have made a clean a bit too more
aggressive.
Fix #262
=> Fix handling of absolute url in kiwix-serve.

src/server/kiwix-serve.cpp
This way a client may filter the catalog by category.
=> Allow to search the catalog by tags.

Changelog, src/manager/kiwix-manage.cpp
=> [manage] Do not show all books if id has been provided on command line.

Changelog, src/manager/kiwix-manage.cpp
Note that no option is allowed if several zim files are specified.
Fix #236
=> [manage] Allow user to add several zim files to library in the same time.

src/manager/meson.build, src/reader/meson.build, src/searcher/meson.build, src/server/meson.build
Fix #250
Fix also https://github.com/openzim/zimwriterfs/issues/72
=> Remove rpath in installed binaries.

src/server/kiwix-serve.cpp
libmicrohttpd has no support of poll on windows.
=> Do not use POLL on windows.

Changelog, src/server/kiwix-serve.cpp
=> Add --nodatealiases command line option #269

Changelog, static/server/home.html.tmpl
=> Display cards in 3 columns properly

Changelog, src/manager/kiwix-manage.cpp
=> Better kiwix-manage usage()

Changelog, src/manager/kiwix-manage.cpp, src/server/kiwix-serve.cpp
=> Better kiwix-serve usage()

Changelog, static/server/home.html.tmpl, static/server/taskbar.css
=> Add footer

src/server/kiwix-serve.cpp
=> Adapt kiwix-serve to the new api to filter library.

src/manager/kiwix-manage.cpp, src/reader/kiwix-read.cpp, src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
=> Remove include of unistd.h

src/manager/kiwix-manage.cpp
If we want to return `-1` we must use a integer, not a bool.
=> Use integer to store the returnCode.

static/server/taskbar.css, static/server/taskbar.html.part
=> Better kiwix-serve content (because of taskbar) top-padding

src/server/kiwix-serve.cpp
this parameter get a string that contains all tags to exclude separated by
a ";". The kiwix::Filter() is set with this rejected tags.
=> add notag parameter to the api

src/server/kiwix-serve.cpp
works like https://github.com/kiwix/kiwix-tools/pull/305
=> search api accept multiple tags parameter

src/server/kiwix-serve.cpp
=> Fix buggy --nolibrarybutton (regression)

Changelog, meson.build, src/server/kiwix-serve.cpp
=> Nodatealiases regression fix

Changelog, src/manager/kiwix-manage.cpp
=> Fix argument parsing

src/reader/kiwix-read.cpp
Old API is not threadsafe and is deprecated.
Need kiwix/kiwix-lib#374
=> Use new suggestion API of kiwix-lib.

src/searcher/kiwix-search.cpp
Suggested by Debian's lintian.
=> Improve grammar in kiwix-search help

.github/workflows/package.yml, debian/control
Basically the same as https://github.com/openzim/libzim/pull/380.
=> PPA: Drop eoan and sync with proper Debian package

src/server/kiwix-serve.cpp
We had an old branch with this small improvement
=> Better PID type conversion

src/manager/kiwix-manage.cpp, src/server/kiwix-serve.cpp
=> Adapt kiwix-tools to the new libkiwix headers.

src/server/kiwix-serve.cpp
=> Add missing break in the switch case.

docker/server/README.md, docker/server/docker-compose.yml.example
Add docker-compose for kiwix-server
- run docker-compose with local file.
- run docker-compose with remote file.
=> Add docker-compose for kiwix-server

src/server/kiwix-serve.cpp
=> Mentioned --monitorLibrary in the help message

src/server/kiwix-serve.cpp
Fixes #473 
Needs https://github.com/kiwix/libkiwix/pull/622.
=> Add startup message to provide http url to server

src/version.h
Fixes #438
Depends on https://github.com/openzim/libzim/pull/656 and https://github.com/kiwix/libkiwix/pull/665
=> Print dependence versions

src/server/kiwix-serve.cpp
Part 2 of https://github.com/kiwix/libkiwix/pull/668
=> Change kiwix::fileExists to kiwix::fileReadable

src/server/kiwix-serve.cpp
Fixes the extra issue reported in https://github.com/kiwix/kiwix-tools/issues/521
=> Add root location in startup message

meson.build
Depends on https://github.com/openzim/libzim/pull/662
=> New deps needed

src/searcher/kiwix-search.cpp
=> Fixed armhf_static CI build

src/server/kiwix-serve.cpp
=> Exit if wrong argument given to kiwix-serve

src/server/kiwix-serve.cpp
=> Do not allow multiple values for same option

.github/workflows/docker.yml, docker/Dockerfile
Simpler dockerfile is less maintenance 😉
=> Simpler dockerfile

docs/kiwix-serve.rst
=> Doc update for `/catalog/v2/entries?count=0`

docker/server/README.md
Create dedicated section for Docker Compose.
=> Dedicated Docker Compose section

Changelog, meson.build
=> Release 3.6.0

meson.build
@mgautierfr Sorry, I don't have found a better way
=> Check max version of libzim/libkiwix

meson.build
Libkiwix has move to major version 14 https://github.com/kiwix/libkiwix/pull/1116
=> Update libkiwix dependency version

.github/workflows/package.yml, debian/control
Add new distribution Ubuntu noble. Unfortunately we requires nos latest version of libzim9 and libkiwix14 which are not on Debian, so I had to comment out all Debian related recipes. See https://github.com/kiwix/libkiwix/issues/1115
=> Refresh deb packages CI/CD

meson.build
Depends on kiwix/libkiwix#1133
=> libkiwix now identifies itself as libkiwix

docs/kiwix-serve.rst
Fixes https://github.com/kiwix/libkiwix/issues/1029
=> Clear support list of kiwix-serve supported browsers

.github/workflows/ci.yml
=> Compile in release mode for Windows
