meson.build
I was running into the build error of:
```
[1/1] Linking target src/server/kiwix-serve
FAILED: src/server/kiwix-serve 
c++    -o src/server/kiwix-serve 'src/server/kiwix-serve@exe/static_server_server-resources.cpp.o' 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' '-Wl,--no-undefined' '-Wl,--as-needed' '-pthread' '-L/usr/local/lib/x86_64-linux-gnu' '-L/usr/local/lib' '-L/usr/local/lib/pugixml-1.8' '-lkiwix' '-lzim' '-llzma' '-licui18n' '-licuuc' '-licudata' '-lpugixml' '-lxapian' '-lmicrohttpd' '-lctpp2' 
/usr/bin/ld: src/server/kiwix-serve@exe/kiwix-serve.cpp.o: undefined reference to symbol 'compress'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
This change fixes that since it adds the proper linker …
=> meson: Add missing zlib dependency

src/server/kiwix-serve.cpp
This PR fix a lot of things :
- Do not send two extra bytes at end of compressed answers.
- Do not segfault on long running kiwix-serve session.
- Better handle compression for big content.
This PR fix a lot of silly bug. Please, reviews are welcomed :)
=> Kiwix serve.bugfix

src/server/kiwix-serve.cpp
I think this piece of code was necessary in the past but should not be necessary anymore. ZIM articles are full HTML pages.
=> ZIM/libzim/libkiwix should provide full HTML DOM

src/reader/kiwix-read.cpp
All code using tree.h where commented.
As tree.h where install by kiwix-lib and we removed it there, let's remove
its use here.
=> Remove use of tree.h

src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
Default `protocolPrefix` for the kiwix-lib searcher is `zim:://`.
We have to change it to `/` for all searcher we create else the search's
results will have a `zim://...` url, which will obviously won't work.
=> Correctly set ProtocolPrefix and SearchProtocolPrefix for searcher.

src/server/kiwix-serve.cpp
Global search is made only on the global task bar.
Task bar display in the article should provide full text search only
if the zim file has associated full text index.
This is done by having a `NULL` searcher. However, commit `558a0375`
return the globalSearcher if no searcher is associated to a zim.
This commit associate a `NULL` searcher to the zim, so we will not use
the globalSearcher.
=> Do not do globalSearch if the zim file has no full text index.

src/server/kiwix-serve.cpp
We should not cache search results for searches done from the welcome page. When we add or remove zims from the library, search results for a given query should take these changes into account.
This pull request fixes the issue.
=> do not cache results for searches from the welcome page

src/server/kiwix-serve.cpp
Almost nothing should be relative to the executable directory.
Content coming from the user should be relative to where the user
is (its working directory).
Fixes #70.
=> Relative paths are relative to current directory not executable.

src/server/kiwix-serve.cpp
In case of infinit redirection, if we post-increment the loop counter,
we will exit the loop when loopCounter will be 42 and increment it.
So loop counter will be 43.
Let's pre-increment the counter to still compare with 42 (more consistancy)
Fix #168
=> Correctly pre-increment the loopCounter.

src/installer/meson.build, src/manager/meson.build, src/reader/meson.build, src/searcher/meson.build, src/server/meson.build
Let's set RPATH of installed binaries, this way, we will be able to
run dynamically linked binaries without changing LD_LIBRARY_PATH.
=> Set rpath of the installed binaries.

src/server/kiwix-serve.cpp
Avoid going over argc during argument parsing.
=> Fix crash when --library is provided but no actual library path is.

src/server/kiwix-serve.cpp
Use `size_t` instead of `unsigned int` to ensure proper size on 64-bit platforms
=> Fix #211: getMimeTypeForFile does not handle files without extensions correctly

src/server/kiwix-serve.cpp
Make sure that <netinet/in.h> is included as per POSIX spec.
=> Fix #213: sockaddr_in is undefined when compiling on FreeBSD

src/manager/kiwix-manage.cpp, src/server/kiwix-serve.cpp
Mingw doesn't implement them. So, we should not use it.
I suppose that it was working before because mingw package for debian trusty
simply no provides a "thread" header.
We may face to include the native "thread" header.
=> Do not use this_thread::sleep or thread::hardware_concurrency.

src/manager/kiwix-manage.cpp
The variable `zimPathToSave` is used to store the option passed by the
user.
If we reuse this variable to store the real path to use for the first
zim file, then we will mess the path to save of other zim files.
Let's use a local variable here.
Fix #288
=> Correctly set the zimPathToSave if there are several zim file to add.

src/server/kiwix-serve.cpp
Now `kiwix-serve` trust the information in the library.xml.
We do not open all zim file at startup and so kiwix-serve starts faster.
Need kiwix/kiwix-lib#314
Fix #319
=> [serve] Trust the library by default.

src/server/kiwix-serve.cpp
Shortcuts `-i` and `-z`, while mentioned in usage, are not usable.
* allowed shortcut `-i` for `--address`
* allowed shortcut `-z` for `--nodatealiases`
=> added shortcut for options --address and --nodatealiases

Changelog, src/server/kiwix-serve.cpp
Add a new `-b` `--blockexternallinks` option to kiwix-serve
triggering the corresponding response taskbar option in kiwix-lib.
This is tied to kiwix/kiwix-lib/pull/330 so **obviously**, don't move forward on this until we're good on kiwix-lib.
=> Add support for external links blocking in kiwix-serve

src/server/kiwix-serve.cpp
Now that libzim doesn't inculde "windows.h" in its public headers it fails
if we don't include it.
=> Include missing "windows.h"

docker/server/Dockerfile
Alternative impl of #404 
Usage would be
```sh
docker build . -t kiwix/kiwix-serve:latest --build-arg ARCH="arm32v7a/"
docker build . -t kiwix/kiwix-serve:latest --build-arg ARCH="amd64"
```
Yes, the arg needs to end with a slash, that's what makes it work if you don't set anything. This will download the `armhf` release of kiwix-tools for any `ARCH` starting with `arm`. All others would use the `x68_64` version.
=> Add support for ARM in Docker

.github/workflows/docker.yml, docker/Dockerfile, docker/README.md, docker/server/Dockerfile
- added a new generic kiwix/kiwix-tools image
- kiwix/kiwix-serve now based on kiwix/kiwix-tools ; with its entrypoint
- both images are built with official binary distribution
- both images are built on github action and pushed to both docker.io and ghcr.io
- both images are multi-arch and support arm/v7, arm64 and amd64
- built on release published or workflow_dispatch event (to be triggered by kiwix-build)
Fixes #373 and #410
=> CI built docker image

src/server/kiwix-serve.cpp
=> This fixes the redundant error message when the kiwix server fails to start

src/server/kiwix-serve.cpp
Fixes #243 and #502
Depends on kiwix/libkiwix#636
Library reloading updates metadata of existing books, adds new books and/or removes books that are no longer present in the library XML file.
=> Library reloading on SIGHUP

src/server/kiwix-serve.cpp
Fixes #476
If started with the `--monitorLibrary` option (or its short variant `-M`) `kiwix-serve` monitors the input library files and reloads the library automatically.
Only the timestamp of the library file(s) is monitored (if there are multiple library files the most recently modified file's timestamp is used). The library is reloaded when the monitored timestamp grows.
SIGHUP makes `kiwix-serve` to reload the library unconditionally (even if the file hasn't changed).
=> kiwix-serve can monitor and reload the library automatically

src/server/kiwix-serve.cpp
=> Add -h/--help option to kiwix-serve

docker/Dockerfile
PR#489 (01430603b689bdb213acd7cf6eaa712173dea59f) introduced dumb-init for better signals handling.
While this has the intended effect, it was done ny downloading the dumb-init static bin into the image… only using the amd64 version.
Ever since, the image(s) have been broken for armv7 and arm64.
As dumb-init doesn't provide 32b arm binary and because it's such a simple/small code, this fix compiles it in a builder shallow image ; ensuring we're getting an appropriate binary for the target arch.
We are also statically linking against musl-C as this is supported by dumb-init and is much smaller than glibc.
=> Fixed docker image for non-amd64 platforms

meson.build
We are using `kiwix::Reader` and `kiwix::Searcher` which are now deprecated. (See kiwix/libkiwix#674)
Remove `werror` until we fix this.
=> Do not compile with `werror=true`.

docker/Dockerfile
Without `ca-certificates` package, `dumb-init` download fails with a HTTPS error.
Tested on a Raspberry Pi 4.
=> Fix dumb-init HTTPS download in Dockerfile

debian/control
```
Our libzim packages are "7.2.0~focal" but the ~ means that "7.2.0" is greater than
"7.2.0~focal" so the dependency can't be satisfied. Depending on "7.2.0~" will
allow "7.2.0~focal" to satisfy the dependency. Same for libkiwix.
```
=> PPA: Fix libzim-dev and libkiwix-dev dependencies

src/server/kiwix-serve.cpp
Fixes #106
Part 2: https://github.com/kiwix/libkiwix/pull/700
=> Add ip connection limit option

src/server/kiwix-serve.cpp
On recent mingw compiler, `stat` is already defined the same way we do.
So we don't need to do it.
=> Do not define stat if not necessary.

src/manager/kiwix-manage.cpp
=> Make kiwix-manage return with something !0 if something went wrong

src/server/kiwix-serve.cpp, src/version.h
Previously, there was an inconsistent usage of no namespace vs namespace.
This change fixes that by correctly adding std:: whenever required.
Adds iostream header in src/version.h to fix cout/cerr problems.
Fixes #563
=> Add iostream header and namespace std

src/server/kiwix-serve.cpp
Usage mentions that the `rootLocation` defaults to `/` while it was not. It defaulted to an empty string.
While it defaulting to `""` or `"/"` has no technical consequence: libkiwix's server normalizes the requested rootLocation ; it leads to users setting a `"/"`-prefixed rootLocation when customizing it, resulting in double-slashed print of the URL
to access kiwix-serve at.
This harmonizes usage and actual default, fixing the URL print.
=> Default kiwix-serve's rootLocation to "/"

Changelog, meson.build
* Remove last reference to kiwix-read tool (@legoktm #569)
kiwix-serve
-----------
* Fix broken indentation in usage (@kelson42 #560)
* Exit if wrong arguments are passed (@kelson42 #567)
* Do not allow multiple values for same option (@juuz0 #564)
* Fix default location of "rootLocation" (@rgaudin #571)
* [DOCKER] Change default port to 8080 (@neyder #581)
* [DOCKER] Simplify dockerfile (@rgaudin #582)
kiwix-manage
------------
* Fix man page (@kelson42 #576)
=> New version 3.4.0

docker/server/docker-compose.yml.example
My docker compose did not like the wildcard at the beginning. I had to surround it with quotes before it would run.
=> Docker compose example: Surround wildcard statement in quotes

.github/workflows/docker.yml, .github/workflows/package.yml
Do avoid CI warnings because these old actions rely on deprecated Node.js 12
=> Update GitHub workflow actions

docs/kiwix-serve.rst
Fixes #595
It turned out that the `count` parameter of the `/catalog/v2/entries` endpoint was documented incorrectly. I both fixed and elaborated the documentation. 
This PR is secretly published on RTD. See the documentation of the relevant section at https://kiwix-tools.readthedocs.io/en/documentation_of_catalog_pagination/kiwix-serve.html#catalog-v2-entries
=> Fixed & elaborated documentation of OPDS catalog pagination

docs/kiwix-serve.rst
Fixes #593 
- HTTP API endpoints have been categorized as public/private
- Added missing information about the `/search` endpoint
The changes can be checked on [RTD](https://kiwix-tools.readthedocs.io/en/documentation/)
=> Documentation updates

.github/workflows/docker.yml, Changelog, docker/Dockerfile
- Fixes the release filename for arm64 and armv7
- Add new architectures for i386 and armv6
**Attention ⚠️**: this currently points to non-existing files as the filenames have changed in nightly but we haven't released since the change. Can be merged but should not be run until next release.
=> Docker images for new architectures

.github/workflows/ci.yml, .github/workflows/package.yml, src/manager/kiwix-manage.cpp, src/server/kiwix-serve.cpp
See kiwix/libkiwix#991 for more details
=> Adapt to new api introduced in kiwix/libkiwix#991

docs/conf.py, docs/kiwix-serve.rst
=> Fixed the "book name"-vs-"ZIM name" bug in docs

docs/conf.py
Back when the `kiwix-serve` documentation was introduced (in the end of 2022) the [theme choice question was raised and a deliberate selection in favour of the RTD Sphinx theme was made](https://github.com/kiwix/kiwix-tools/pull/586#issuecomment-1365831225).
Then sometime in 2023 the [default theme on Read-the-Docs was changed to Alabaster](https://github.com/readthedocs/readthedocs.org/issues/10692).
This change enforces the old theme (sphinx_rtd_theme).
=> Reinstated the RTD Sphinx Theme for documentation

.github/workflows/ci.yml
Running the CI on push only trigger the CI on a push on the current repository. It works on PR based on local branch but not for PR from remote repository.
=> Run the CI on pull_request.

docs/kiwix-serve.rst, src/man/kiwix-serve.1, src/server/kiwix-serve.cpp
Fixes #545 
depends on https://github.com/kiwix/libkiwix/pull/1074
=> Add IPv6 support to Kiwix Server

.github/workflows/ci.yml, debian/control, meson.build, src/manager/kiwix-manage.cpp, src/searcher/kiwix-search.cpp, src/server/kiwix-serve.cpp
Compilation of kiwix-tools is broken on Windows.
But let's setup the CI to validate the PR (to be fixed)
=> Add a Windows CI.

src/server/kiwix-serve.cpp
This changes the logic to use the refactored `getBestPublicIps` so kiwix-serve can display all attached ips based on the protocol that was requested by the user.
Fixes #703
Relies on https://github.com/kiwix/libkiwix/pull/1132
=> kiwix-serve displays both protocol attached ips

docker/Dockerfile, docker/server/Dockerfile
- **Added unpriviliged user for executing kiwix-serve**
This minimizes the code that runs on elevated privileges and allows to execute the Docker-container in rootless mode, enhancing overall security.
- **Switched to new key-value-format**
Following Docker recommendations, all LABEL key-value pairs should be of the structure "key=value" and not "key value".
=> [Docker] kiwix-serve image to use unprivileged user
